[ 2024-03-11 23:35:47,560 ] 130 root - INFO - Initializing model building.
[ 2024-03-11 23:35:50,989 ] 69 root - INFO - Starting incremental hyperparameter tuning for XGBoost classifier with MLflow tracking.
[ 2024-03-11 23:35:51,284 ] 864 hyperopt.tpe - INFO - build_posterior_wrapper took 0.001034 seconds
[ 2024-03-11 23:35:51,284 ] 900 hyperopt.tpe - INFO - TPE using 0 trials
[ 2024-03-11 23:35:51,288 ] 53 root - ERROR - Error during XGBoost incremental objective: Found input variables with inconsistent numbers of samples: [5090096, 10167006]
[ 2024-03-11 23:35:51,288 ] 180 hyperopt.fmin - ERROR - job exception: Error occured in python script name [/Users/siddhant/Project2/Bank_functions/src/models/train_model1.py] line number [47] error message[Found input variables with inconsistent numbers of samples: [5090096, 10167006]]
[ 2024-03-11 23:35:51,289 ] 85 root - ERROR - Error during XGBoost hyperparameter tuning: Error occured in python script name [/Users/siddhant/Project2/Bank_functions/src/models/train_model1.py] line number [47] error message[Found input variables with inconsistent numbers of samples: [5090096, 10167006]]
[ 2024-03-11 23:35:51,289 ] 142 root - ERROR - Error in model building process: Error occured in python script name [/Users/siddhant/Project2/Bank_functions/src/models/train_model1.py] line number [74] error message[Error occured in python script name [/Users/siddhant/Project2/Bank_functions/src/models/train_model1.py] line number [47] error message[Found input variables with inconsistent numbers of samples: [5090096, 10167006]]]
